# Generated by Django 5.1.7 on 2025-04-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_otp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='email',
        ),
    ]
